
export default [ 
  { name: 'Malbec', value: 'malbec'},
  { name: 'Cabernet Sauvignon', value: 'cabernet_sauvignon'},
  { name: 'Merlot', value: 'merlot'},
  { name: 'Syrah', value: 'syrah'},
  { name: 'Cabernet Franc', value: 'cabernet_franc'},
  { name: 'Pinot Noir', value: 'pinot_noir'},
  { name: 'Bonarda', value: 'bonarda'},
  { name: 'Carmenere', value: 'carmenere'},
  { name: 'Petit Verdot', value: 'petit_verdot'},
  { name: 'Tannat', value: 'tannat'},
  { name: 'Tempranillo', value: 'tempranillo'},
  { name: 'Sangiovese', value: 'sangiovese'},
  { name: 'Nebbiolo', value: 'nebbiolo'},
  { name: 'Carignan', value: 'carignan'},
  { name: 'Aglianico', value: 'aglianico'},
  { name: 'Graciana', value: 'graciana'},
  { name: 'Caladoc', value: 'caladoc'},
  { name: 'Marselan', value: 'marselan'},
  { name: 'Grenache', value: 'grenache'},
  { name: 'Ancellotta', value: 'ancellotta'},
  { name: 'Barbera', value: 'barbera'},
  { name: 'Chardonnay', value : 'chardonnay' },
  { name: 'Sauvignon Blanc', value : 'sauvignon_blanc' },
  { name: 'Torrontes', value : 'torrontes' },
  { name: 'Pinot Gris', value : 'pinot_gris' },
  { name: 'Viognier', value : 'viognier' },
  { name: 'Semillón', value : 'semillon' },
  { name: 'Chenin Blanc', value : 'chenin_blanc' },
  { name: 'Riesling', value : 'riesling' },
  { name: 'Tocai', value : 'tocai' },
  { name: 'Albariño', value : 'albariño' },
  { name: 'Marsanne', value : 'marsanne' },
  { name: 'Gewurztraminer', value : 'gewurstraminer' },
  { name: 'Petit Manseng', value : 'petit_manseng' },
  { name : 'Fiano', value : 'fiano' },
  { name : 'Canarí', value : 'canari' }
]


export const VARIETIES_LABELS = {
  'malbec': 'Malbec',
  'cabernet_sauvignon': 'Cabernet Sauvignon',
  'merlot': 'Merlot',
  'syrah': 'Syrah',
  'cabernet_franc': 'Cabernet Franc',
  'pinot_noir': 'Pinot Noir',
  'bonarda': 'Bonarda',
  'carmenere': 'Carmenere',
  'petit_verdot': 'Petit Verdot',
  'tannat': 'Tannat',
  'tempranillo': 'Tempranillo',
  'sangiovese': 'Sangiovese',
  'nebbiolo': 'Nebbiolo',
  'carignan': 'Carignan',
  'aglianico': 'Aglianico',
  'aspirant_bouchet': 'Aspirant Bouchet',
  'graciana': 'Graciana',
  'caladoc': 'Caladoc',
  'marselan': 'Marselan',
  'grenache': 'Grenache',
  'ancellotta': 'Ancellotta',
  'barbera': 'Barbera',
  'chardonnay' : 'Chardonnay',
  'sauvignon_blanc' : 'Sauvignon Blanc',
  'torrontes' : 'Torrontes',
  'pinot_gris' : 'Pinot Gris',
  'viognier' : 'Viognier',
  'semillon' : 'Semillón',
  'chenin_blanc' : 'Chenin Blanc',
  'riesling' : 'Riesling',
  'tocai' : 'Tocai',
  'albariño' : 'Albariño',
  'marsanne' : 'Marsanne',
  'gewurstraminer' : 'Gewurztraminer',
  'petit_manseng' : 'Petit Manseng',
  'fiano'  : 'Fiano',
  'canari' : 'Canarí',
}