import { Platform, Dimensions } from 'react-native'
import { colors, utils } from 'theme'

export default {
  welcome: {
    navBarHidden: true,
    statusBarColor: 'rgba(0,0,0,0.2)',
    drawUnderStatusBar: Platform.OS !== 'ios',
    navBarTitleTextCentered: true,
  },

  subView: {
    navBarTextFontFamily: 'Helvetica',
    navBarTextColor: '#000000',
    navBarTextFontSize: 17 / utils.fontScale, 
    drawUnderNavBar: true,
    navBarTransparent: true,
    navBarTranslucent: true,
    navBarBackgroundColor: false,
    navBarButtonColor: '#000000',
    topBarElevationShadowEnabled: false,
    navBarHeight: 82,
    navBarTopPadding: 24,
    navBarNoBorder: true,
    screenBackgroundColor: 'white',
    statusBarColor: 'rgba(0,0,0,0.2)',
    drawUnderStatusBar: Platform.OS !== 'ios',
    navBarTitleTextCentered: true,
  },

  tabs: {
    tabBarBackgroundColor: '#34404c',
    tabBarButtonColor: '#FFFFFF',
    tabBarSelectedButtonColor: colors.primaryColor,
    tabBarSelectedLabelColor: colors.primaryColor,
    tabBarHideShadow: false,
    tabBarTextFontFamily: 'Raleway-Regular',
    screenBackgroundColor: '#FFF',
    tabBarLabelColor: '#FFF',
    statusBarColor: 'rgba(0,0,0,0.2)',
    drawUnderStatusBar: Platform.OS !== 'ios',
    navBarHeight: 82,
    navBarTopPadding: 24,
    navBarNoBorder: true,
    selectedTabFontSize: 12 / utils.fontScale,
    tabFontSize: 12 / utils.fontScale,
    statusBarTextColorSchemeSingleScreen: 'light',
    navBarTitleTextCentered: true,
  },

  tab: {
    statusBarTextColorScheme: 'light',
    statusBarTextColorSchemeSingleScreen: 'light',
    navBarBackgroundColor: colors.primaryColor,
    navBarTextColor: '#FFF',
    navBarTextFontSize: 20 / utils.fontScale,
    navBarButtonColor: '#FFF',
    navBarTextFontFamily: 'Raleway-Regular',
    navBarTitleTextCentered: true,
    // navBarHeight: 82, 
    // navBarTopPadding: 24,
    // statusBarColor: 'rgba(0,0,0,0.2)',
    // drawUnderStatusBar: Platform.OS !== 'ios',
  },

  modal: {
    statusBarTextColorScheme: 'dark',
    statusBarColor: 'rgba(0,0,0,0.2)',
    statusBarTextColorSchemeSingleScreen: 'dark',
    screenBackgroundColor: 'white',
    navBarBackgroundColor: false,
    navBarTextColor: '#000000',
    navBarTextFontSize: 20 / utils.fontScale,
    navBarButtonColor: '#000000',
    navBarTextFontFamily: 'Raleway-Regular',
    navBarNoBorder: true,
    navBarTitleTextCentered: true,
    navBarBackgroundColor: '#eee',
  },
}