export default [
    { "country_states": "Afghanistan" },
    { "country_states": "Albania" },
    { "country_states": "Algeria" },
    { "country_states": "Andorra" },
    { "country_states": "Angola" },
    { "country_states": "Antigua and Barbuda" },
    { "country_states": "Argentina" },
    { "country_states": "Armenia" },
    { "country_states": "Australia" },
    { "country_states": "Austria" },
    { "country_states": "Azerbaijan" },
    { "country_states": "The Bahamas" },
    { "country_states": "Bahrain" },
    { "country_states": "Bangladesh" },
    { "country_states": "Barbados" },
    { "country_states": "Belarus" },
    { "country_states": "Belgium" },
    { "country_states": "Belize" },
    { "country_states": "Benin" },
    { "country_states": "Bhutan" },
    { "country_states": "Bolivia" },
    { "country_states": "Bosnia and Herzegovina" },
    { "country_states": "Botswana" },
    { "country_states": "Brazil" },
    { "country_states": "Brunei" },
    { "country_states": "Bulgaria" },
    { "country_states": "Burkina Faso" },
    { "country_states": "Burundi" },
    { "country_states": "Cabo Verde" },
    { "country_states": "Cambodia" },
    { "country_states": "Cameroon" },
    { "country_states": "Canada" },
    { "country_states": "Central African Republic" },
    { "country_states": "Chad" },
    { "country_states": "Chile" },
    { "country_states": "China" },
    { "country_states": "Colombia" },
    { "country_states": "Comoros" },
    { "country_states": "Congo, Democratic Republic of the" },
    { "country_states": "Congo, Republic of the" },
    { "country_states": "Costa Rica" },
    { "country_states": "Côte d’Ivoire" },
    { "country_states": "Croatia" },
    { "country_states": "Cuba" },
    { "country_states": "Cyprus" },
    { "country_states": "Czech Republic" },
    { "country_states": "Denmark" },
    { "country_states": "Djibouti" },
    { "country_states": "Dominica" },
    { "country_states": "Dominican Republic" },
    { "country_states": "East Timor" },
    { "country_states": "Ecuador" },
    { "country_states": "Egypt" },
    { "country_states": "El Salvador" },
    { "country_states": "Equatorial Guinea" },
    { "country_states": "Eritrea" },
    { "country_states": "Estonia" },
    { "country_states": "Eswatini" },
    { "country_states": "Ethiopia" },
    { "country_states": "Fiji" },
    { "country_states": "Finland" },
    { "country_states": "France" },
    { "country_states": "Gabon" },
    { "country_states": "The Gambia" },
    { "country_states": "Georgia" },
    { "country_states": "Germany" },
    { "country_states": "Ghana" },
    { "country_states": "Greece" },
    { "country_states": "Grenada" },
    { "country_states": "Guatemala" },
    { "country_states": "Guinea" },
    { "country_states": "Guinea-Bissau" },
    { "country_states": "Guyana" },
    { "country_states": "Haiti" },
    { "country_states": "Honduras" },
    { "country_states": "Hungary" },
    { "country_states": "Iceland" },
    { "country_states": "India" },
    { "country_states": "Indonesia" },
    { "country_states": "Iran" },
    { "country_states": "Iraq" },
    { "country_states": "Ireland" },
    { "country_states": "Israel" },
    { "country_states": "Italy" },
    { "country_states": "Jamaica" },
    { "country_states": "Japan" },
    { "country_states": "Jordan" },
    { "country_states": "Kazakhstan" },
    { "country_states": "Kenya" },
    { "country_states": "Kiribati" },
    { "country_states": "Korea, North" },
    { "country_states": "Korea, South" },
    { "country_states": "Kosovo" },
    { "country_states": "Kuwait" },
    { "country_states": "Kyrgyzstan" },
    { "country_states": "Laos" },
    { "country_states": "Latvia" },
    { "country_states": "Lebanon" },
    { "country_states": "Lesotho" },
    { "country_states": "Liberia" },
    { "country_states": "Libya" },
    { "country_states": "Liechtenstein" },
    { "country_states": "Lithuania" },
    { "country_states": "Luxembourg" },
    { "country_states": "Madagascar" },
    { "country_states": "Malawi" },
    { "country_states": "Malaysia" },
    { "country_states": "Maldives" },
    { "country_states": "Mali" },
    { "country_states": "Malta" },
    { "country_states": "Marshall Islands" },
    { "country_states": "Mauritania" },
    { "country_states": "Mauritius" },
    { "country_states": "Mexico" },
    { "country_states": "Micronesia, Federated States of" },
    { "country_states": "Moldova" },
    { "country_states": "Monaco" },
    { "country_states": "Mongolia" },
    { "country_states": "Montenegro" },
    { "country_states": "Morocco" },
    { "country_states": "Mozambique" },
    { "country_states": "Myanmar (Burma)" },
    { "country_states": "Namibia" },
    { "country_states": "Nauru" },
    { "country_states": "Nepal" },
    { "country_states": "Netherlands" },
    { "country_states": "New Zealand" },
    { "country_states": "Nicaragua" },
    { "country_states": "Niger" },
    { "country_states": "Nigeria" },
    { "country_states": "North Macedonia" },
    { "country_states": "Norway" },
    { "country_states": "Oman" },
    { "country_states": "Pakistan" },
    { "country_states": "Palau" },
    { "country_states": "Panama" },
    { "country_states": "Papua New Guinea" },
    { "country_states": "Paraguay" },
    { "country_states": "Peru" },
    { "country_states": "Philippines" },
    { "country_states": "Poland" },
    { "country_states": "Portugal" },
    { "country_states": "Qatar" },
    { "country_states": "Romania" },
    { "country_states": "Russia" },
    { "country_states": "Rwanda" },
    { "country_states": "Saint Kitts and Nevis" },
    { "country_states": "Saint Lucia" },
    { "country_states": "Saint Vincent and the Grenadines" },
    { "country_states": "Samoa" },
    { "country_states": "San Marino" },
    { "country_states": "Sao Tome and Principe" },
    { "country_states": "Saudi Arabia" },
    { "country_states": "Senegal" },
    { "country_states": "Serbia" },
    { "country_states": "Seychelles" },
    { "country_states": "Sierra Leone" },
    { "country_states": "Singapore" },
    { "country_states": "Slovakia" },
    { "country_states": "Slovenia" },
    { "country_states": "Solomon Islands" },
    { "country_states": "Somalia" },
    { "country_states": "South Africa" },
    { "country_states": "Spain" },
    { "country_states": "Sri Lanka" },
    { "country_states": "Sudan" },
    { "country_states": "Sudan, South" },
    { "country_states": "Suriname" },
    { "country_states": "Sweden" },
    { "country_states": "Switzerland" },
    { "country_states": "Syria" },
    { "country_states": "Taiwan" },
    { "country_states": "Tajikistan" },
    { "country_states": "Tanzania" },
    { "country_states": "Thailand" },
    { "country_states": "Togo" },
    { "country_states": "Tonga" },
    { "country_states": "Trinidad and Tobago" },
    { "country_states": "Tunisia" },
    { "country_states": "Turkey" },
    { "country_states": "Turkmenistan" },
    { "country_states": "Tuvalu" },
    { "country_states": "Uganda" },
    { "country_states": "Ukraine" },
    { "country_states": "United Arab Emirates" },
    { "country_states": "United Kingdom" },
    { "country_states": "United States" },
    { "country_states": "Uruguay" },
    { "country_states": "Uzbekistan" },
    { "country_states": "Vanuatu" },
    { "country_states": "Vatican City" },
    { "country_states": "Venezuela" },
    { "country_states": "Vietnam" },
    { "country_states": "Yemen" },
    { "country_states": "Zambia" },
    { "country_states": "Zimbabwe" }
]