export default [
    { "country_states": "Alabama (AL)" },
    { "country_states": "Alaska (AK)" },
    { "country_states": "Arizona (AZ)" },
    { "country_states": "Arkansas (AR)" },
    { "country_states": "California (CA)" },
    { "country_states": "Colorado (CO)" },
    { "country_states": "Connecticut (CT)" },
    { "country_states": "Delaware (DE)" },
    { "country_states": "District of Columbia (DC)" },
    { "country_states": "Florida (FL)" },
    { "country_states": "Georgia (GA)" },
    { "country_states": "Hawaii (HI)" },
    { "country_states": "Idaho (ID)" },
    { "country_states": "Illinois (IL)" },
    { "country_states": "Indiana (IN)" },
    { "country_states": "Iowa (IA)" },
    { "country_states": "Kansas (KS)" },
    { "country_states": "Kentucky (KY)" },
    { "country_states": "Louisiana (LA)" },
    { "country_states": "Maine (ME)" },
    { "country_states": "Maryland (MD)" },
    { "country_states": "Massachusetts (MA)" },
    { "country_states": "Michigan (MI)" },
    { "country_states": "Minnesota (MN)" },
    { "country_states": "Mississippi (MS)" },
    { "country_states": "Missouri (MO)" },
    { "country_states": "Montana (MT)" },
    { "country_states": "Nebraska (NE)" },
    { "country_states": "Nevada (NV)" },
    { "country_states": "New Hampshire (NH)" },
    { "country_states": "New Jersey (NJ)" },
    { "country_states": "New Mexico (NM)" },
    { "country_states": "New York (NY)" },
    { "country_states": "North Carolina (NC)" },
    { "country_states": "North Dakota (ND)" },
    { "country_states": "Ohio (OH)" },
    { "country_states": "Oklahoma (OK)" },
    { "country_states": "Oregon (OR)" },
    { "country_states": "Pennsylvania (PA)" },
    { "country_states": "Rhode Island (RI)" },
    { "country_states": "South Carolina (SC)" },
    { "country_states": "South Dakota (SD)" },
    { "country_states": "Tennessee (TN)" },
    { "country_states": "Texas (TX)" },
    { "country_states": "Utah (UT)" },
    { "country_states": "Vermont (VT)" },
    { "country_states": "Virginia (VA)" },
    { "country_states": "Washington (WA)" },
    { "country_states": "West Virginia (WV)" },
    { "country_states": "Wisconsin (WI)" },
    { "country_states": "Wyoming (WY)" }
]